apiVersion: v1
kind: Secret
metadata:
  name: telegraf-secret
type: Opaque
stringData:
  INFLUXDB_DB: telegraf
  INFLUXDB_URL: http://influxdb-service:8086
  INFLUXDB_USER: root
  INFLUXDB_PASSWORD: root