apiVersion: v1
kind: Service
metadata:
  name: ftps-service
  labels:
    app: ftps
spec:
  selector:
    app: ftps
  type: LoadBalancer
  ports:
    - port: 20
      name: ftp-data
      targetPort: 20
    - port: 21
      name: ftp-command
      targetPort: 21
    - port: 21000
      name: ftp-psv
      targetPort: 21000
